/**
 * Sample US Pizza Malaysia outlets for development and demo deployments.
 * Skips insert if the table already has rows.
 * @param {import('knex').Knex} knex
 */
exports.seed = async function seed(knex) {
  const [{ count }] = await knex('us_pizza_outlets').count('* as count');
  if (Number(count) > 0) return;

  await knex('us_pizza_outlets').insert([
    {
      outlet_id: 'UP001',
      outlet_name: 'US Pizza SS2 Petaling Jaya',
      address: '24, Jalan SS 2/61, SS 2, 47300 Petaling Jaya, Selangor',
      state: 'Selangor',
      city: 'Petaling Jaya',
      phone: '03-7874 8822',
      opening_hours: '11:00 AM – 10:00 PM',
      location_url: 'https://maps.google.com/?q=US+Pizza+SS2',
    },
    {
      outlet_id: 'UP002',
      outlet_name: 'US Pizza Subang Jaya',
      address: '12, Jalan SS 15/4, Subang Jaya, 47500 Selangor',
      state: 'Selangor',
      city: 'Subang Jaya',
      phone: '03-5632 1188',
      opening_hours: '11:00 AM – 10:00 PM',
      location_url: 'https://maps.google.com/?q=US+Pizza+Subang+Jaya',
    },
    {
      outlet_id: 'UP003',
      outlet_name: 'US Pizza Shah Alam',
      address: 'G-26, Kompleks PKNS, Seksyen 14, 40000 Shah Alam, Selangor',
      state: 'Selangor',
      city: 'Shah Alam',
      phone: '03-5510 7744',
      opening_hours: '11:00 AM – 10:00 PM',
      location_url: 'https://maps.google.com/?q=US+Pizza+Shah+Alam',
    },
    {
      outlet_id: 'UP004',
      outlet_name: 'US Pizza Klang',
      address: '32, Jalan Meru, 41050 Klang, Selangor',
      state: 'Selangor',
      city: 'Klang',
      phone: '03-3342 9900',
      opening_hours: '11:00 AM – 10:00 PM',
      location_url: 'https://maps.google.com/?q=US+Pizza+Klang',
    },
    {
      outlet_id: 'UP005',
      outlet_name: 'US Pizza Cheras',
      address: '88, Jalan Cheras, Taman Midah, 56000 Kuala Lumpur',
      state: 'Kuala Lumpur',
      city: 'Cheras',
      phone: '03-9101 2233',
      opening_hours: '11:00 AM – 10:30 PM',
      location_url: 'https://maps.google.com/?q=US+Pizza+Cheras',
    },
    {
      outlet_id: 'UP006',
      outlet_name: 'US Pizza Bukit Bintang',
      address: 'Lot G-018, Sungei Wang Plaza, Bukit Bintang, 55100 Kuala Lumpur',
      state: 'Kuala Lumpur',
      city: 'Bukit Bintang',
      phone: '03-2143 5566',
      opening_hours: '10:30 AM – 10:30 PM',
      location_url: 'https://maps.google.com/?q=US+Pizza+Bukit+Bintang',
    },
    {
      outlet_id: 'UP007',
      outlet_name: 'US Pizza Setapak',
      address: '15, Jalan Genting Klang, Setapak, 53300 Kuala Lumpur',
      state: 'Kuala Lumpur',
      city: 'Setapak',
      phone: '03-4141 7788',
      opening_hours: '11:00 AM – 10:00 PM',
      location_url: 'https://maps.google.com/?q=US+Pizza+Setapak',
    },
    {
      outlet_id: 'UP008',
      outlet_name: 'US Pizza Penang Georgetown',
      address: '102, Jalan Macalister, 10400 George Town, Penang',
      state: 'Penang',
      city: 'George Town',
      phone: '04-226 8899',
      opening_hours: '11:00 AM – 10:00 PM',
      location_url: 'https://maps.google.com/?q=US+Pizza+Penang',
    },
    {
      outlet_id: 'UP009',
      outlet_name: 'US Pizza Bayan Lepas',
      address: '18, Medan Bayan, Bayan Lepas, 11900 Penang',
      state: 'Penang',
      city: 'Bayan Lepas',
      phone: '04-641 2233',
      opening_hours: '11:00 AM – 10:00 PM',
      location_url: 'https://maps.google.com/?q=US+Pizza+Bayan+Lepas',
    },
    {
      outlet_id: 'UP010',
      outlet_name: 'US Pizza Ipoh',
      address: '55, Jalan Sultan Idris Shah, 30000 Ipoh, Perak',
      state: 'Perak',
      city: 'Ipoh',
      phone: '05-241 6677',
      opening_hours: '11:00 AM – 10:00 PM',
      location_url: 'https://maps.google.com/?q=US+Pizza+Ipoh',
    },
    {
      outlet_id: 'UP011',
      outlet_name: 'US Pizza Johor Bahru',
      address: '12, Jalan Austin Heights 8/2, Taman Mount Austin, 81100 Johor Bahru',
      state: 'Johor',
      city: 'Johor Bahru',
      phone: '07-358 9900',
      opening_hours: '11:00 AM – 10:00 PM',
      location_url: 'https://maps.google.com/?q=US+Pizza+Johor+Bahru',
    },
    {
      outlet_id: 'UP012',
      outlet_name: 'US Pizza Skudai',
      address: '8, Jalan Skudai, 81300 Johor Bahru, Johor',
      state: 'Johor',
      city: 'Skudai',
      phone: '07-558 1122',
      opening_hours: '11:00 AM – 10:00 PM',
      location_url: 'https://maps.google.com/?q=US+Pizza+Skudai',
    },
    {
      outlet_id: 'UP013',
      outlet_name: 'US Pizza Melaka',
      address: '22, Jalan Merdeka, 75000 Melaka',
      state: 'Melaka',
      city: 'Melaka',
      phone: '06-283 4455',
      opening_hours: '11:00 AM – 10:00 PM',
      location_url: 'https://maps.google.com/?q=US+Pizza+Melaka',
    },
    {
      outlet_id: 'UP014',
      outlet_name: 'US Pizza Kuantan',
      address: '9, Jalan Teluk Sisek, 25000 Kuantan, Pahang',
      state: 'Pahang',
      city: 'Kuantan',
      phone: '09-514 7788',
      opening_hours: '11:00 AM – 10:00 PM',
      location_url: 'https://maps.google.com/?q=US+Pizza+Kuantan',
    },
    {
      outlet_id: 'UP015',
      outlet_name: 'US Pizza Kota Kinabalu',
      address: 'Lot 2-08, Suria Sabah, 88000 Kota Kinabalu, Sabah',
      state: 'Sabah',
      city: 'Kota Kinabalu',
      phone: '088-488 990',
      opening_hours: '11:00 AM – 10:00 PM',
      location_url: 'https://maps.google.com/?q=US+Pizza+Kota+Kinabalu',
    },
  ]);
};
